### ISSUE TITLE
User story: Save to favorites

### ISSUE THREAD

**Issue by KevinBjarnemark** [KevinBjarnemark/bottle-post-recipes#10]
EPIC: [Which epic does this relate to?]

As a logged-in user, I want to save recipes so that I can easily access them later.

**Acceptance Criteria**

- Users can save links to recipes on their account by clicking a button. 

**Tasks**

- [ ] Design a save recipe button

- [ ] Design a section that lists all saved recipes.

- [ ] Implement a saving system that stores recipe links for individual users.
