### ISSUE TITLE
User story: Bottle post system

### ISSUE THREAD

**Issue by KevinBjarnemark** [KevinBjarnemark/bottle-post-recipes#5]
EPIC: Bottle post sharing notification system

Story points: 5

As a user, I want to review other users' recipes and have the ability to boost or downgrade them, so I can help improve the quality of content in the app.

**Acceptance Criteria**

- Users can boost a recipe they think is beneficial.

- Users can downgrade a recipe they think is not helpful or of lower quality.

- The app reflects changes in the recipe's visibility or ranking based on user actions (boost or downgrade).

**Tasks**

- [x] Implement functionality to allow users to boost a recipe.

- [x] Implement functionality to allow users to downgrade a recipe.

- [x] Update recipe rankings or visibility based on user inputs.
