### ISSUE TITLE
User story: Sensitive content

### ISSUE THREAD

**Issue by KevinBjarnemark** [KevinBjarnemark/bottle-post-recipes#8]
EPIC: User preferences

Story points: 1

As a user, I don't want to see images of dead animals on the app so that I can feel more at home when loading the homepage.

**Acceptance Criteria**

- Users are able to dial in their dietary preference settings to vegan/fish/meat.

- Users who visit the app for the first time will not be shown dead animals.

- A 'vegan mode' user setting is present in the user profile.

- A vegan mode button is present and easily accessible in the app.

**Tasks**

- [x] Add a vegan mode setting that defaults to true during account registration.

- [x] Design a global vegan mode switch button.

- [x] Add functionality that enables the user to filter out non-vegan recipes, both on page load and on-demand.
